AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM CI/CD Example Application
Resources:
 HelloWorldFunction:
   Type: AWS::Serverless::Function
   Properties:
     CodeUri: hello-world/
     Handler: app.lambda_handler
     Runtime: python3.9
     Events:
       ApiGateway:
         Type: Api
         Properties:
           Path: /hello
           Method: GET
Outputs:
 ApiUrl:
   Description: "API Gateway endpoint URL"
   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"